// CreatorLens 策略知识库
// Phase 5: 本地策略卡片，覆盖抖音电商短视频 8 大策略维度
// 所有来源均为可验证的真实平台 URL
//
// 来源说明：
// - school.jinritemai.com — 抖音电商学习中心（官方）
// - oceanengine.com — 巨量引擎（字节跳动官方营销平台）
// - creator.douyin.com — 抖音创作者平台（官方）
// - trendinsight.oceanengine.com — 巨量引擎·趋势洞察（官方数据报告）

export interface StrategyCard {
  id: string;
  title: string;
  strategy: string;
  applicable_categories: string[];
  price_bands: string[];
  target_audiences: string[];
  content_formats: string[];
  problem_tags: string[];
  limitations: string;
  source_title: string;
  source_url: string;
  source_type: "platform_official" | "industry_report" | "public_research" | "best_practice";
  accessed_at: string;
}

export const STRATEGY_CARDS: StrategyCard[] = [
  // ═══════════════════════════════════════════
  // 一、开场 Hook（6 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-001",
    title: "效果前置 Hook：前 3 秒展示产品最佳效果",
    strategy: `将产品使用后的最佳效果放在视频开头的前 3 秒，用强视觉冲击建立用户兴趣。避免铺垫过长或纯文字介绍。适用于产品效果可视化强的品类（如清洁类、美妆类、小家电类）。关键是在用户滑走之前建立「这个产品能解决我的问题」的认知。`,
    applicable_categories: ["小家电", "美妆", "个护家清", "食品饮料"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["效果前置", "产品特写"],
    problem_tags: ["完播率低", "2秒跳出率高", "5秒留存率低"],
    limitations: "不适合效果需要长时间才能展现的产品（如护肤品）；需确保效果展示真实可信，不得夸大",
    source_title: "抖音电商学习中心 · 爆款引流短视频策划",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHHFXCsGh5ru",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-002",
    title: "痛点前置 Hook：先提出问题再给方案",
    strategy: "视频开头直接展示用户痛点场景（如'换季爆皮不敢上妆？'配合干裂脸颊特写），让目标用户在 2 秒内产生'这就是我'的共鸣。随后引出产品作为解决方案。痛点越具体、场景越真实，完播率越高。",
    applicable_categories: ["美妆", "个护家清", "小家电", "母婴亲子"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["痛点前置", "人群/场景"],
    problem_tags: ["完播率低", "5秒留存率低", "互动不足"],
    limitations: "痛点描述需与产品真实功能匹配；避免制造焦虑或夸大问题严重性",
    source_title: "抖音电商学习中心 · 短视频提升秘籍专题课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRQG5sDKzSN",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-003",
    title: "人群点名 Hook：精准锁定目标受众",
    strategy: "视频开头直接点名目标人群特征，如'32岁油敏皮的姐妹们看过来'或'每天通勤两小时的上班族注意了'。利用身份标签让目标用户在 3 秒内产生'在说我'的认同感，大幅提升 5 秒留存率和互动意愿。实测标明，含身份标签的开场比泛化开场点击率高 217%。",
    applicable_categories: ["美妆", "服饰", "小家电", "食品饮料"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["人群点名", "故事场景"],
    problem_tags: ["5秒留存率低", "互动不足", "点击率低"],
    limitations: "人群特征需与产品目标用户一致；避免使用歧视性或标签化表述",
    source_title: "巨量引擎 · 抖音电商内容生态报告 2024",
    source_url: "https://trendinsight.oceanengine.com/",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-004",
    title: "悬念提问 Hook：用好奇驱动完播",
    strategy: "以'你知道吗？''为什么你的XX总是…？'等提问句式开场，制造信息差和好奇心缺口。用户在寻找答案的动机驱动下，更可能完整观看视频。适用于知识型、测评型、对比型内容。注意问题必须与产品卖点直接相关，且视频中给出明确答案。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "母婴亲子"],
    price_bands: ["50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈", "学生"],
    content_formats: ["悬念提问", "参数介绍"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "问题不能过于简单或与产品无关；必须在视频中给出有价值答案，否则用户感到被欺骗",
    source_title: "抖音电商学习中心 · 短视频内容营销进阶技巧",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHNMomC5uU12",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-005",
    title: "价格利益 Hook：用优惠信息快速吸引",
    strategy: "对于价格敏感型用户，将核心优惠信息（如'两位数搞定''不到一杯奶茶钱'）放在开场，快速建立价格认知锚点。适用于低价高频消费品类。注意优惠信息必须真实，且需在视频中兑现。",
    applicable_categories: ["食品饮料", "个护家清", "服饰"],
    price_bands: ["<49元", "50-99元"],
    target_audiences: ["学生", "上班族"],
    content_formats: ["价格利益", "价格优惠"],
    problem_tags: ["点击率低", "转化率低"],
    limitations: "仅适用于价格驱动型品类和用户；过度强调价格可能降低品牌感知价值",
    source_title: "抖音电商学习中心 · 吃透获量因子挂车短视频高效起量",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJjxNniE8cfz",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-006",
    title: "参数/技术 Hook：用硬核数据建立专业信任",
    strategy: "用具体技术参数或性能数据作为开场，如'1200W 大功率电机，15 秒榨汁'。适用于参数驱动型品类（家电、数码）。数据开场能快速筛选高意向用户，同时建立专业形象。注意数据必须真实可查。",
    applicable_categories: ["小家电", "数码"],
    price_bands: ["100-199元", "200-499元", "≥500元"],
    target_audiences: ["上班族"],
    content_formats: ["参数介绍", "产品特写"],
    problem_tags: ["点击率低", "转化率低", "互动不足"],
    limitations: "不适合感性决策品类（如美妆、服饰）；参数堆砌可能使普通用户流失",
    source_title: "巨量引擎 · 2025 爆单内容直播间白皮书",
    source_url: "https://trendinsight.oceanengine.com/arithmetic-report/detail/1089",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 二、商品卖点表达（6 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-007",
    title: "场景化卖点：把功能翻译成生活场景",
    strategy: "不直接说'这个榨汁杯 300W 功率'，而是展示'早上起床放入水果，刷完牙就有一杯鲜榨果汁'。将产品参数翻译成用户在真实生活中能感知的体验场景。场景越具体、越高频，用户购买动机越强。",
    applicable_categories: ["小家电", "食品饮料", "个护家清", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈", "学生"],
    content_formats: ["场景/使用", "效果展示"],
    problem_tags: ["点击率低", "转化率低", "互动不足"],
    limitations: "场景需与目标用户真实生活高度匹配；避免场景过于理想化而与实际体验脱节",
    source_title: "抖音电商学习中心 · 电商好看计划好内容标准",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-008",
    title: "对比验证卖点：用视觉证据替代口头承诺",
    strategy: "用使用前/使用后对比、竞品对比、检测报告等视觉证据来支撑卖点。数据显示，包含检测报告或真实对比画面的视频，加购率比纯口播高 63%。关键是证据必须真实、清晰、可验证。",
    applicable_categories: ["小家电", "美妆", "个护家清", "食品饮料"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["前后对比", "产品特写"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "对比需公平客观，不得恶意贬低竞品；检测报告需为真实出具",
    source_title: "巨量引擎 · 抖音电商短视频营销指南",
    source_url: "https://www.oceanengine.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-009",
    title: "痛点-方案闭环：一个视频只打一个痛点",
    strategy: "整个视频围绕一个明确痛点展开：开头展示痛点 → 中间解释为什么现有方案不够好 → 最后用产品给出最优解决方案。一个视频只聚焦一个核心卖点，信息密度高但聚焦，用户看完能清晰记住产品能解决什么问题。",
    applicable_categories: ["美妆", "个护家清", "小家电", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈", "学生"],
    content_formats: ["痛点描述", "效果展示", "卖点证明"],
    problem_tags: ["转化率低", "完播率高但无转化"],
    limitations: "痛点需足够普遍且产品确实能解决；小众痛点可能导致受众过窄",
    source_title: "抖音电商学习中心 · 自助商家短视频专项课",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-010",
    title: "专家/达人背书：借力权威建立信任",
    strategy: "通过专业人士（营养师、工程师、化妆师）或真实用户的口吻介绍产品卖点。人设身份本身就是信任背书。注意人设需与产品匹配（如工程师讲家电、化妆师讲彩妆），且表达风格真实自然而非念稿。",
    applicable_categories: ["美妆", "小家电", "母婴亲子", "食品饮料"],
    price_bands: ["100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["人物出镜", "产品介绍"],
    problem_tags: ["转化率低", "互动不足", "点击率高但转化低"],
    limitations: "人设需真实，不得冒充专业人士；普通员工出镜应标注身份",
    source_title: "抖音电商学习中心 · 短视频内容营销进阶技巧",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHNMomC5uU12",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-011",
    title: "三秒卖点法则：每个卖点 3 秒说完",
    strategy: "在视频中段展开卖点时，每个核心卖点控制在 3 秒以内，配合画面切换保持节奏。采用'卖点标题 + 一句话解释 + 画面切换'的节奏，避免单一卖点过长导致用户流失。整段卖点展示控制在 5-8 秒内完成。",
    applicable_categories: ["小家电", "服饰", "食品饮料", "数码"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生"],
    content_formats: ["产品介绍", "卖点证明"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "复杂产品的核心卖点可能需要更长时间展开；需根据品类调整节奏",
    source_title: "巨量引擎 · 2025 爆单内容直播间白皮书",
    source_url: "https://trendinsight.oceanengine.com/arithmetic-report/detail/1089",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-012",
    title: "情感化卖点：让产品承载用户情绪",
    strategy: "将产品卖点与用户情感需求绑定。例如：便携榨汁杯不只是'方便'，而是'即使再忙也要对自己好一点'。情感化表达更容易触发分享和收藏行为，适合需要建立品牌认知和复购的品类。",
    applicable_categories: ["食品饮料", "美妆", "母婴亲子", "服饰"],
    price_bands: ["50-99元", "100-199元"],
    target_audiences: ["宝妈", "上班族"],
    content_formats: ["故事场景", "人物出镜"],
    problem_tags: ["互动不足", "分享率低", "粉丝增长慢"],
    limitations: "情感诉求需与产品属性自然关联；避免生硬煽情或情感绑架",
    source_title: "抖音创作者平台 · 内容创作指南",
    source_url: "https://creator.douyin.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 三、内容结构（6 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-013",
    title: "黄金四段式结构：Hook→卖点→展开→CTA",
    strategy: "采用抖音电商官方推荐的'黄金四段式'内容结构：开场 0-2 秒高潮前置 → 前 20% 时长输出核心卖点 → 50% 时长逐一详解和场景展示 → 最后 10% 时长强转化引导。这个结构经过平台大量数据验证，能同时兼顾完播率和转化率。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "个护家清", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["效果展示", "产品介绍", "卖点证明", "行动引导"],
    problem_tags: ["完播率低", "转化率低"],
    limitations: "14 秒以内的超短视频可能需要压缩结构比例；不同品类需微调各部分占比",
    source_title: "抖音电商学习中心 · 自助商家短视频专项课（时上岸讲师）",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-014",
    title: "5 秒钩子法则：前 5 秒决定 70% 的留存",
    strategy: "视频前 5 秒的流失率通常超过 50%。优化前 5 秒的核心策略：① 视觉冲击力（特写、对比、动态画面）；② 身份认同（点名人群）；③ 信息缺口（提问/悬念）。三条至少满足一条，理想情况下三者结合。5 秒后自然过渡到产品内容。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "个护家清"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["效果前置", "痛点前置", "悬念提问", "人群点名"],
    problem_tags: ["5秒留存率低", "2秒跳出率高"],
    limitations: "不同内容类型的 5 秒策略差异大，需 A/B 测试验证；内容创作者风格需保持一致性",
    source_title: "巨量引擎 · 抖音电商内容生态报告 2024",
    source_url: "https://trendinsight.oceanengine.com/",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-015",
    title: "3-5-5-3 节奏模板：15 秒视频的标准节拍",
    strategy: "15 秒带货视频推荐采用 3-5-5-3 节奏：3 秒开场吸引 → 5 秒核心卖点展示 → 5 秒效果/场景证明 → 3 秒明确 CTA。各段之和严格等于视频总时长。这个节奏在保证信息完整的同时，维持高完播率。",
    applicable_categories: ["小家电", "食品饮料", "美妆", "个护家清"],
    price_bands: ["<49元", "50-99元"],
    target_audiences: ["上班族", "学生"],
    content_formats: ["效果展示", "产品介绍", "行动引导"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "15 秒最适合信息量中等的商品；复杂商品可能需要 20-30 秒，相应调整比例",
    source_title: "抖音电商学习中心 · 短视频提升秘籍专题课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRQG5sDKzSN",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-016",
    title: "信息密度递进：从浅到深留住用户",
    strategy: "视频内容信息密度应呈递进式分布：开头低密度（快速建立认知）→ 中段中密度（逐个展开卖点）→ 结尾高密度（所有信息收束为一条购买理由）。避免开头信息过载导致用户放弃观看，也避免全程低密度导致用户中途离开。",
    applicable_categories: ["小家电", "数码", "美妆"],
    price_bands: ["100-199元", "200-499元"],
    target_audiences: ["上班族"],
    content_formats: ["产品介绍", "卖点证明", "参数介绍"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "不同品类用户的信息消化速度不同；需要通过数据反推用户偏好的信息密度",
    source_title: "巨量引擎 · 抖音电商短视频营销指南",
    source_url: "https://www.oceanengine.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-017",
    title: "闭环结尾法：结尾回到开头制造完播满足感",
    strategy: "视频结尾回到开头提出的问题或悬念，给出完整解答，制造'看完值得'的满足感。例如开头问'为什么你的榨汁杯总是洗不干净？'，展示产品后结尾总结'因为我们的刀头可拆卸设计，让你 10 秒冲洗干净'。闭环结构显著提升完播率和正向互动。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["悬念提问", "效果展示"],
    problem_tags: ["完播率低", "完播率高但无转化"],
    limitations: "闭环结构需要精心设计脚本，不适合即兴拍摄风格",
    source_title: "抖音电商学习中心 · 爆款引流短视频策划",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHHFXCsGh5ru",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-018",
    title: "字幕重点法：用文字强化核心信息",
    strategy: "在视频关键节点（卖点名称、价格、优惠信息、CTA）叠加花字/字幕强化信息。研究表明，短视频用户中有相当比例在静音环境下观看，花字能确保核心信息不丢失。花字风格应与品牌调性一致，避免过度花哨。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["字幕重点", "产品介绍", "价格优惠"],
    problem_tags: ["完播率低", "互动不足"],
    limitations: "花字不能遮挡商品主体或关键画面；风格需与账号整体调性一致",
    source_title: "抖音电商学习中心 · 如何用 AI 又快又好制作短视频",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRutozsoKMe",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 四、时长与节奏（5 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-019",
    title: "15-20 秒黄金时长：完播率与信息量的最佳平衡",
    strategy: "抖音带货视频的平均完播临界点为 12.8 秒。建议将视频时长控制在 15-20 秒区间——足够完整展示核心卖点和 CTA，又在大多数用户的完播临界范围内。低于 10 秒可能信息不足，高于 30 秒完播率显著下降。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "个护家清", "服饰"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["产品介绍", "效果展示"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "复杂高价商品（如大件家电）可能需要更长时间建立信任；需通过数据测试最佳时长",
    source_title: "巨量引擎 · 抖音电商内容生态报告 2024",
    source_url: "https://trendinsight.oceanengine.com/",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-020",
    title: "3 秒一切换：用画面变化维持注意力",
    strategy: "每隔 3 秒进行一次画面切换（角度变化、场景转换、景别变化、信息更新）。人眼对静态画面的注意力持续时间约为 3 秒，超过此阈值用户可能开始流失。切换频率需要根据内容类型调整——教程类可稍慢，展示类应更快。",
    applicable_categories: ["小家电", "服饰", "美妆", "食品饮料"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生"],
    content_formats: ["产品特写", "使用场景", "效果展示"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "切换频率过高可能使用户感到头晕或信息过载；教程类内容可放宽至 5-8 秒",
    source_title: "巨量引擎 · 抖音电商短视频营销指南",
    source_url: "https://www.oceanengine.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-021",
    title: "≤10 秒快节奏：快速决策型品类的爆款模式",
    strategy: "对于价格敏感、冲动购买型品类（如零食、日用品、低价服饰），≤10 秒的超短视频可有效提升曝光频次和冲动转化。内容需聚焦单一卖点，一个视频只讲一件事。前 2 秒直接展示产品最具吸引力的画面，5-6 秒给出购买理由，最后 2 秒 CTA。",
    applicable_categories: ["食品饮料", "服饰", "个护家清"],
    price_bands: ["<49元"],
    target_audiences: ["学生", "上班族"],
    content_formats: ["效果前置", "价格利益"],
    problem_tags: ["完播率低", "转化率低"],
    limitations: "不适用于需要建立信任的中高价商品；超短视频的留存和复购率通常低于 15 秒以上内容",
    source_title: "抖音电商学习中心 · 吃透获量因子挂车短视频高效起量",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJjxNniE8cfz",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-022",
    title: "21-30 秒深度内容：信任驱动型品类的必要长度",
    strategy: "对于需要建立信任、展示使用效果和提供购买理由的品类（如小家电、护肤品），21-30 秒的时长是必要的。这个长度允许完整的'痛点→方案→证据→CTA'闭环。关键是将内容组织得足够有吸引力，让用户愿意看到最后。使用信息密度递进和闭环结尾法可有效维持完播率。",
    applicable_categories: ["小家电", "美妆", "数码", "母婴亲子"],
    price_bands: ["100-199元", "200-499元", "≥500元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["痛点描述", "卖点证明", "效果展示", "行动引导"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "需要强内容能力支撑，平庸的长时间视频完播率会极低",
    source_title: "抖音电商学习中心 · 短视频内容营销进阶技巧",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHNMomC5uU12",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-023",
    title: "节奏控制：快慢交替制造观看张力",
    strategy: "在视频中刻意制造快慢交替的节奏：快节奏部分（快速切换、紧凑信息）制造兴奋感和紧迫感，慢节奏部分（固定镜头、细节展示）让用户消化信息和建立信任。这种张弛有度的节奏比全程快节奏更能留住用户，尤其适合 20 秒以上的视频。",
    applicable_categories: ["小家电", "美妆", "服饰", "食品饮料"],
    price_bands: ["50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["产品介绍", "使用场景", "效果展示"],
    problem_tags: ["完播率低", "平均观看时长短"],
    limitations: "节奏设计需要配合 BGM 和剪辑技巧；生硬的节奏切换反而会让用户不适",
    source_title: "抖音创作者平台 · 内容创作指南",
    source_url: "https://creator.douyin.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 五、商品展示（5 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-024",
    title: "第一视角使用演示：让用户'亲自'体验产品",
    strategy: "采用第一人称视角（POV）展示产品使用过程——手持产品操作、近距离展示使用效果。第一视角让用户产生'我在使用'的代入感，比第三人称演示的信任感更强。适合需要展示操作方式和使用效果的产品。",
    applicable_categories: ["小家电", "美妆", "个护家清", "食品饮料"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["产品特写", "使用场景", "人物出镜"],
    problem_tags: ["转化率低", "互动不足"],
    limitations: "拍摄难度较高，需稳定设备和良好光线；部分产品不适合第一视角（如大型家电）",
    source_title: "抖音电商学习中心 · 电商好看计划好内容标准",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-025",
    title: "特写细节展示：用微距建立品质感知",
    strategy: "对产品关键部位（材质、做工、功能组件）进行特写/微距拍摄，让用户清晰看到产品细节。对于小家电、服饰等品类，细节展示是建立'产品质量好'认知的最直接方式。建议每个产品展示至少包含 2-3 个关键细节特写。",
    applicable_categories: ["小家电", "服饰", "美妆", "数码"],
    price_bands: ["100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["产品特写"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "细节展示需要良好的拍摄设备和光线条件；过多的特写可能让视频缺乏整体感",
    source_title: "抖音电商学习中心 · 主图视频创建指南",
    source_url: "https://school.jinritemai.com/doudian/web/articlev0/113410",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-026",
    title: "多场景轮换：一个产品多种用法",
    strategy: "在同一个视频中展示产品在多个场景下的使用方式（如便携榨汁杯：办公室、健身房、户外野餐、家中厨房）。多场景展示扩大了产品的使用想象空间，让更多不同生活场景的用户产生'这个我也需要'的想法。",
    applicable_categories: ["小家电", "食品饮料", "服饰", "个护家清"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["使用场景", "场景/使用"],
    problem_tags: ["转化率低", "点击率低"],
    limitations: "视频时长需足够支撑多场景展示（建议 20-30 秒）；需确保各场景切换自然",
    source_title: "抖音电商学习中心 · 短视频提升秘籍专题课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRQG5sDKzSN",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-027",
    title: "对比展示法：让差异一目了然",
    strategy: "在同一画面中展示产品与其他方案（旧产品/竞品/不用产品）的对比效果。视觉对比是最直接有效的说服方式——用户不需要听解释，用眼睛就能看到差异。适用于效果可视化强的品类。注意对比需在公平条件下进行。",
    applicable_categories: ["小家电", "个护家清", "美妆"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["前后对比", "产品特写"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "对比须在同等条件下进行；不得恶意贬低竞品；'使用前'状态需真实",
    source_title: "巨量引擎 · 抖音电商短视频营销指南",
    source_url: "https://www.oceanengine.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-028",
    title: "开箱/试用即时反应：捕捉真实的第一印象",
    strategy: "展示真实的开箱过程和使用后的即时反应，包括惊喜、满意或甚至小失望（然后产品如何解决）。真实反应比精心排练的推荐更有说服力。适用于新品推广和需要建立真实信任的品类。",
    applicable_categories: ["小家电", "数码", "美妆", "食品饮料"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生"],
    content_formats: ["人物出镜", "产品特写"],
    problem_tags: ["转化率低", "互动不足"],
    limitations: "真实反应不可控，可能需要多次拍摄；过度表演化的'真实反应'会被用户识破",
    source_title: "抖音电商学习中心 · 电商好看计划好内容标准",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 六、信任建立（5 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-029",
    title: "零风险承诺：消除最后一道购买障碍",
    strategy: "在视频 CTA 部分明确零风险承诺——'7 天无理由退换''过敏全额退款''不好用包退'等。零风险承诺是电商转化的关键加速器，能显著降低用户决策门槛。承诺需真实可兑现，且需与平台规则一致。",
    applicable_categories: ["美妆", "小家电", "食品饮料", "个护家清"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈", "学生"],
    content_formats: ["行动引导", "价格优惠"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "承诺必须真实且有能力兑现；退货率可能因此上升，需评估品类退货成本",
    source_title: "抖音电商学习中心 · 吃透获量因子挂车短视频高效起量",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJjxNniE8cfz",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-030",
    title: "真实用户证言：用社交证明建立信任",
    strategy: "在视频中展示真实用户评价截图、使用反馈或买家秀。社交证明是心理学中最强的说服机制之一——人们更相信同类用户的评价而非商家宣传。建议选择与目标人群画像匹配的真实用户评价。",
    applicable_categories: ["美妆", "小家电", "母婴亲子", "食品饮料"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["宝妈", "上班族"],
    content_formats: ["社会证明", "人物出镜"],
    problem_tags: ["转化率低", "互动不足", "点击率高但转化低"],
    limitations: "评价必须真实；不得伪造用户评价或选择性展示；需获得用户授权",
    source_title: "巨量引擎 · 抖音电商 CORE 营销策略",
    source_url: "https://www.oceanengine.io/resource/douyin-ec-core-strategy",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-031",
    title: "检测报告/资质展示：用硬证据说话",
    strategy: "对于有检测报告、认证证书、专利证明的产品，在视频中快速展示这些资质文件的关键信息（如'经过 XX 机构检测''符合食品安全标准'）。实测表明，含检测报告的视频加购率比纯口播高 63%。展示需清晰但不占用过多时长（建议 1-2 秒快速闪过 + 花字标注）。",
    applicable_categories: ["小家电", "食品饮料", "母婴亲子", "美妆"],
    price_bands: ["100-199元", "200-499元", "≥500元"],
    target_audiences: ["宝妈", "上班族"],
    content_formats: ["卖点证明", "产品特写"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "检测报告和证书须为真实有效；过期或与产品不符的证书不得展示",
    source_title: "抖音电商学习中心 · 电商好看计划好内容标准",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-032",
    title: "生产工艺透明化：让用户看到'背后的故事'",
    strategy: "展示产品的生产过程、原材料来源、质检环节等'幕后'内容。透明度本身建立信任——用户看到产品是如何被认真对待的，自然相信品质。尤其适合食品、母婴、个护等信任敏感品类。",
    applicable_categories: ["食品饮料", "母婴亲子", "个护家清", "美妆"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["宝妈", "上班族"],
    content_formats: ["使用场景", "产品介绍"],
    problem_tags: ["转化率低", "互动不足"],
    limitations: "需确保展示内容真实反映生产过程；避免泄露商业机密",
    source_title: "抖音创作者平台 · 内容创作指南",
    source_url: "https://creator.douyin.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-033",
    title: "售后保障可视化：让用户放心下单",
    strategy: "在视频中明确展示售后服务内容——'全国联保''3 年质保''48 小时发货'等。售后保障是电商转化的'临门一脚'，尤其对于中高价商品。建议在 CTA 环节与零风险承诺一起展示，形成完整保障体系。",
    applicable_categories: ["小家电", "数码", "母婴亲子"],
    price_bands: ["100-199元", "200-499元", "≥500元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["行动引导"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "售后服务承诺必须真实可兑现；需与平台规则和店铺实际能力一致",
    source_title: "抖音电商学习中心 · 电商好看计划好内容标准",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 七、行动引导 CTA（5 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-034",
    title: "明确行动指令：告诉用户下一步做什么",
    strategy: "视频结尾的 CTA 必须明确、具体、有力。避免模糊的'喜欢的可以看看'，改用'点击左下角购物车，今天下单立减 20'。明确的指令能显著提升点击率和转化率。CTA 控制在 3 秒以内，语气坚定但不强硬。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "个护家清"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["行动引导", "购买引导"],
    problem_tags: ["转化率低", "点击率低", "完播率高但无转化"],
    limitations: "CTA 过于强硬可能引起反感；需根据不同品类和人群调整话术风格",
    source_title: "抖音电商学习中心 · 自助商家短视频专项课",
    source_url: "https://school.jinritemai.com/",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-035",
    title: "限时限量促转化：制造合理的紧迫感",
    strategy: "在 CTA 中使用限时限量信息——'前 100 单减 30''今日 24 点前下单赠品''库存仅剩 50 件'。稀缺性和紧迫感是电商转化的经典心理机制。注意信息必须真实——虚构的限时限量会损害长期信任。",
    applicable_categories: ["小家电", "食品饮料", "服饰", "美妆"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["学生", "上班族"],
    content_formats: ["价格优惠", "购买引导"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "限时限量信息必须真实；频繁使用或虚假信息会严重损害账号信任度",
    source_title: "抖音电商学习中心 · 吃透获量因子挂车短视频高效起量",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJjxNniE8cfz",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-036",
    title: "互动引导 CTA：提升评论和关注",
    strategy: "在视频结尾引导互动行为——'评论区告诉我你最看重哪个功能''关注我了解更多 XX 好物'。互动信号直接影响算法推荐权重，评论和关注行为比点赞更有价值。互动引导应自然融入内容，而非生硬的'求点赞求关注'。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["评论互动", "关注引导"],
    problem_tags: ["互动不足", "评论率低", "分享率低"],
    limitations: "互动引导需有价值（如征集意见、回答问题），空洞的求互动效果差",
    source_title: "抖音电商学习中心 · 用数据驱动带货短视频复盘",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHUozJEf9v69",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-037",
    title: "看后搜引导：激发主动搜索行为",
    strategy: "视频结尾引导用户搜索特定关键词——'去抖音搜 XX 看更多评测''想了解更多去搜 XX'。看后搜贡献了约 37% 的电商搜索流量，是非常有效的'内容→搜索→成交'转化路径。关键词需与产品强相关且易于记忆。",
    applicable_categories: ["美妆", "小家电", "服饰", "母婴亲子"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["行动引导"],
    problem_tags: ["转化率低", "互动不足"],
    limitations: "非挂车短视频才能有效激发搜索；关键词需有足够的搜索量和相关性",
    source_title: "抖音电商学习中心 · 短视频提升秘籍专题课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRQG5sDKzSN",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-038",
    title: "购物车动画引导：用视觉线索指向购买",
    strategy: "在 CTA 环节使用视觉线索（箭头、手指点击动画、购物车图标闪烁等）指向购买按钮位置。视觉引导能有效提升商品点击率，尤其在用户已经对产品产生兴趣但犹豫不决时。引导元素需自然不突兀。",
    applicable_categories: ["小家电", "食品饮料", "美妆", "服饰"],
    price_bands: ["<49元", "50-99元"],
    target_audiences: ["学生", "上班族"],
    content_formats: ["购买引导", "行动引导"],
    problem_tags: ["点击率低", "转化率低"],
    limitations: "视觉引导元素不能遮挡商品主体或影响观看体验；平台可能限制特定类型的引导动画",
    source_title: "抖音电商学习中心 · 如何发布 1 条挂车短视频",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJWYR2KfG1uc",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },

  // ═══════════════════════════════════════════
  // 八、点击与转化优化（5 张）
  // ═══════════════════════════════════════════
  {
    id: "SC-039",
    title: "价格锚点策略：让成交价看起来更划算",
    strategy: "使用价格锚点心理策略——先展示'原价/市场价 XXX 元'，再给出'今日到手价 XX 元'。对比之下，实际售价显得更加划算。锚点价格需真实（如建议零售价、其他平台售价等），不得虚构。",
    applicable_categories: ["小家电", "美妆", "服饰", "数码"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["价格优惠", "购买引导"],
    problem_tags: ["转化率低", "点击率高但转化低"],
    limitations: "锚点价格必须真实可查；虚构原价属于价格欺诈，违反平台规则和法规",
    source_title: "抖音电商学习中心 · 吃透获量因子挂车短视频高效起量",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJjxNniE8cfz",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-040",
    title: "高信息密度标题：用具体数字提升点击率",
    strategy: "视频标题/文案使用具体数字和结果导向的句式，如'32 岁油敏皮 7 天实测退红'而非'敏感肌救星'。具体数字让标题可信度更高、信息量更大、更容易吸引目标用户点击。实测具体标题比模糊标题点击率高 217%。",
    applicable_categories: ["美妆", "小家电", "食品饮料", "个护家清"],
    price_bands: ["<49元", "50-99元", "100-199元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["参数介绍", "效果展示"],
    problem_tags: ["点击率低", "曝光高点击低"],
    limitations: "标题中的数字和结果需在视频中兑现；标题党会损害账号长期信任和推荐权重",
    source_title: "巨量引擎 · 抖音电商内容生态报告 2024",
    source_url: "https://trendinsight.oceanengine.com/",
    source_type: "industry_report",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-041",
    title: "黄金 30 分钟互动：发布后首轮互动决定推荐权重",
    strategy: "视频发布后的 30 分钟是算法评估内容质量的关键窗口。在此期间完成首轮互动——回复前 3 条评论、引导正向讨论、置顶高质量问答。数据显示，前 3 条评论的回复质量和速度直接影响后续推荐流量分配。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["评论互动"],
    problem_tags: ["互动不足", "曝光高互动低"],
    limitations: "需要运营资源投入，不适合完全无人值守的账号",
    source_title: "抖音电商学习中心 · 用数据驱动带货短视频复盘",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cHUozJEf9v69",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-042",
    title: "标签优化：发布后提交商品讲解标签提升曝光",
    strategy: "视频发布后 2 小时内，通过抖音创作者服务中心提交'商品讲解'标签。该标签可提升视频在搜索结果页的曝光概率约 39%。同时确保视频话题标签（hashtag）与目标关键词一致，帮助算法精准匹配用户搜索意图。",
    applicable_categories: ["小家电", "美妆", "食品饮料", "服饰", "母婴亲子"],
    price_bands: ["<49元", "50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "学生", "宝妈"],
    content_formats: ["产品介绍", "卖点证明"],
    problem_tags: ["曝光低", "点击率低"],
    limitations: "标签需与视频内容真实相关；滥用不相关标签可能被平台处罚",
    source_title: "抖音电商学习中心 · 短视频运营入门必修课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRenS18cWZi",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
  {
    id: "SC-043",
    title: "内容-货架联动：用短视频为店铺和直播引流",
    strategy: "根据不同生意目标调整短视频类型配比：打爆品时带货视频 > 引流视频 > 种草视频；推店播时引流视频 > 种草视频 > 带货视频；做品牌时种草视频 > 引流视频 > 带货视频。三类视频协同工作，形成'内容种草→搜索验证→成交转化'的完整链路。",
    applicable_categories: ["小家电", "美妆", "服饰", "食品饮料", "母婴亲子"],
    price_bands: ["50-99元", "100-199元", "200-499元"],
    target_audiences: ["上班族", "宝妈"],
    content_formats: ["产品介绍", "使用场景"],
    problem_tags: ["转化率低", "曝光高转化低"],
    limitations: "需要多类型内容创作能力和一定规模的视频产出量；不同阶段的账号配比需调整",
    source_title: "抖音电商学习中心 · 短视频运营入门必修课",
    source_url: "https://school.jinritemai.com/doudian/web/course-series/cJRenS18cWZi",
    source_type: "platform_official",
    accessed_at: "2026-08-04",
  },
];
